<?php
/**
 * @var $block ProductForm
 * @var $escaper \Magento\Framework\Escaper
 */

use Improntus\Rebill\Block\Adminhtml\ProductForm;
use Improntus\Rebill\Helper\Config;

/** @var Config $configHelper */
$configHelper = $this->helper(Config::class);
?>
<div id="rebill-frequency-modal">
    <table>
        <thead>
            <tr>
                <th><?= /** @noEscape */__('ID') ?></th>
                <th><?= /** @noEscape */__('Frequency') ?></th>
                <th><?= /** @noEscape */__('Frequency Type') ?></th>
                <th><?= /** @noEscape */__('Max Recurring Payments') ?></th>
                <th><?= /** @noEscape */__('Price') ?></th>
                <th><?= /** @noEscape */__('SignUp Cost') ?></th>
                <th><?= /** @noEscape */__('Actions') ?></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "rebill_product_form": {
                "attributes": <?= /** @noEscape */ $block->getRebillAttributesJson() ?>,
                "product_type": "<?= /** @noEscape */ $block->getProductType() ?>",
                "is_product_child": <?= /** @noEscape */ (int)$configHelper->isProductChild($block->getProduct()) ?>,
                "product_price": <?= /** @noEscape */ $block->getProduct()->getPrice() ?>
            }
        }
    }
</script>
