<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var Rebill $block
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Block\Sales\Order\Rebill;

$order = $block->getInfo()->getOrder();
$payment = $order->getPayment();
$additionalInformation = $payment->getAdditionalInformation();
?>
<p><?= $escaper->escapeHtml($additionalInformation['method_title']) ?></p>
<ul class="status-payment-rebill" style="list-style: none;padding: 0;">
    <?php if (isset($additionalInformation['status_detail'])): ?>
        <li><?= $escaper->escapeHtml(__($additionalInformation['status_detail'])) ?></li>
    <?php endif ?>
    <?php if (isset($additionalInformation['card'])): ?>
        <li><strong><?= /** @noEscape */ __('Card Holder Name') ?>: </strong> <?= $escaper->escapeHtml($additionalInformation['card']['holder_name'])?></li>
        <li><strong><?= /** @noEscape */ __('Last 4 four digits') ?>: </strong><?= $escaper->escapeHtml($additionalInformation['card']['last4'])?></li>
    <?php endif ?>
</ul>
