<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block View
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Helper\Config;
use Magento\Catalog\Block\Product\View;

/** @var Config $configHelper */
$configHelper = $this->helper(Config::class);
$rebillDetails = $configHelper->getProductRebillSubscriptionDetails($block->getProduct());
?>
<?php if ($rebillDetails['enable_subscription'] && ($labelType = $configHelper->getProductLabel()) !== 'none') : ?>
    <div class="rebill-product-label">
        <?php if ($labelType == 'text') : ?>
            <span class="rebill-label-text"><?= $escaper->escapeHtml($configHelper->getProductLabelCustomText()) ?></span>
        <?php else : ?>
            <div class="rebill-label-rebill-logo">
                <img src="<?= /** @noEscape */ $block->getViewFileUrl('Improntus_Rebill::images/rebill_logo.png'); ?>" alt="<?= /** @noEscape */ __('Product Subscription with Rebill') ?>">
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
