<?php
/**
 * @var $block ListProduct
 * @var $escaper \Magento\Framework\Escaper
 */

use Improntus\Rebill\Helper\Config;
use Magento\Catalog\Block\Product\ListProduct;

/** @var Config $configHelper */
$configHelper = $this->helper(Config::class);
?>
<?php if (($labelType = $configHelper->getProductLabel()) !== 'none') : ?>
    <script>
        require(['jquery'], function ($) {
            $(document).ready(function () {
                let labelType = '<?= $escaper->escapeHtml($labelType) ?>';
                let labelRebillLogo = '<?= /** @noEscape  */ $block->getViewFileUrl('Improntus_Rebill::images/rebill_logo.png'); ?>';
                let labelEl = $('<div class="rebill-product-label"></div>');
                if (labelType === 'text') {
                    labelEl.append($('<span class="rebill-label-text"></span>').text('<?= $escaper->escapeHtml($configHelper->getProductLabelCustomText()) ?>'));
                } else {
                    labelEl.append($('<div class="rebill-label-rebill-logo"></div>')
                        .append($(`<img src='${labelRebillLogo}' alt='<?= /** @noEscape  */ __('Product Subscription with Rebill') ?>'/>`)));
                }
                $.ajax({
                    url: "<?= /** @noEscape  */ $block->getUrl('rebill/product/labels') ?>",
                    type: 'POST',
                    data: {ids: <?= /** @noEscape  */ json_encode($block->getLoadedProductCollection()->getAllIds()) ?>},
                    dataType: 'json',
                    success: function (data) {
                        $.each(data.products, function (id, value) {
                            $(`#product-item-info_${id} .product-image-photo`).parent().append(labelEl);
                        });
                    }
                });
            });
        });
    </script>
<?php endif; ?>
