<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block View
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Helper\Config;
use Magento\Catalog\Block\Product\View;
use Magento\Framework\Pricing\Helper\Data;

/** @var Config $configHelper */
$configHelper = $this->helper(Config::class);
$product = $block->getProduct();
$details = $configHelper->getProductRebillSubscriptionDetails($product);
/** @var Data $currencyHelper */
$currencyHelper = $this->helper(Data::class);
$isLoggedIn = $configHelper->isLoggedIn();
$onclick = $isLoggedIn ? '' : "onclick=\"window.location.href='{$block->getUrl('customer/account/login')}'\" style=\"cursor:pointer;\"";
?>
<?php if ($details['enable_subscription']) : ?>
    <?php if (!$isLoggedIn) : ?>
        <div class="subscription-text" <?= /** @noEscape */$onclick ?>>
            <span class="text guest-text"><?= $escaper->escapeHtml($configHelper->getGuestCustomerText()) ?></span>
        </div>
    <?php endif ?>
<?php endif ?>
