<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block Edit
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Block\Customer\Edit;
use Magento\Framework\Pricing\Helper\Data;

/** @var Data $currencyHelper */
$currencyHelper = $this->helper(Data::class);
$subscription = $block->getSubscription() ?? [];
$card = $block->getCard($subscription['card']);
$documentTypes = $block->getDocumentTypes($subscription['price']['gateway']['type']);
?>
<div class="rebill-subscription-data">
    <div class="section">
        <span class="section-title"><?= /** @noEscape */__('Product:') ?></span>
        <span class="section-value"><?= $escaper->escapeHtml($subscription['title'] . ' x ' . $subscription['quantity']) ?></span>
    </div>
    <div class="section">
        <span class="section-title"><?= /** @noEscape */__('Status:') ?></span>
        <span class="section-value"><?= $escaper->escapeHtml($subscription['status']) ?></span>
    </div>
    <div class="section">
        <span class="section-title"><?= /** @noEscape */__('Period:') ?></span>
        <span class="section-value"><?= $escaper->escapeHtml($block->getSubscriptionText($subscription)) ?></span>
    </div>
    <div class="section">
        <span class="section-title"><?= /** @noEscape */__('Next payment date:') ?></span>
        <span class="section-value"><?= $escaper->escapeHtml(date('Y-m-d', strtotime($subscription['nextChargeDate']))) ?></span>
    </div>
    <?php if ($subscription['remainingIterations'] > 0) : ?>
        <div class="section">
            <span class="section-title"><?= /** @noEscape */__('Remaining payments:') ?></span>
            <span class="section-value"><?= $escaper->escapeHtml($subscription['remainingIterations']) ?></span>
        </div>
    <?php endif ?>
    <div class="section">
        <span class="section-title"><?= /** @noEscape */__('Current payment method:') ?></span>
        <span class="section-value"><?= $escaper->escapeHtml($block->getPaymentMethod($card)) ?></span>
    </div>
</div>

<?php if ($documentTypes) : ?>
    <div class="rebill-identification-field">
        <div class="type">
            <label for="identification-type"><?= /** @noEscape  */__('Document Type') ?></label>
            <select name="identification_type" id="identification-type">
                <?php foreach ($documentTypes as $documentType) : ?>
                    <option
                        value="<?= $escaper->escapeHtmlAttr($documentType['value']) ?>"><?= $escaper->escapeHtml($documentType['value']) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="value">
            <label for="identification-value"><?= /** @noEscape  */__('Document Number') ?></label>
            <input type="text" id="identification-value" name="identification_value">
        </div>
    </div>
<?php endif ?>
<div id="rebill_elements"></div>

<script>
    require(['jquery', 'rebill'], function ($) {
        let initialization = {
            organization_id: '<?= $escaper->escapeJs($block->getApiUuid()) ?>',
            api_url: 'https://api.rebill.to/v2',
            subscription_id: '<?= $escaper->escapeJs($subscription['id']) ?>',
            customer_token: '<?= $escaper->escapeJs($block->getCustomerToken()) ?>',
        }
        let checkout = new Rebill.PhantomSDK(initialization);

        let cardHolder = {
            name: '<?= $escaper->escapeJs($card['cardHolder']) ?>',
            identification: {
                type: $('#identification-type').val()
            }
        }
        checkout.setCardHolder(cardHolder);
        let errorsMessage = $('.rebill-errors');
        checkout.setCallbacks({
            onSuccess: function (response) {
                errorsMessage.html('');
                window.location.href = '<?= $escaper->escapeUrl($block->getUrl('*/*/*')) ?>';
            },
            onError: function (error) {
                errorsMessage.html('')
                    .append($('<div class="error-message"></div>')
                        .text("<?= /** @noEscape */ __('The payment can\'t be processed, try again with another card.') ?>"));
            },
        });
        checkout.setText({
            card_number: '<?= /** @noEscape */ __('Card Number') ?>',
            pay_button: '<?= /** @noEscape */ __('Update your subscription') ?>',
            error_messages: {
                emptyCardNumber: '<?= /** @noEscape */ __('Enter a card number') ?>',
                invalidCardNumber: '<?= /** @noEscape */ __('Card number is invalid') ?>',
                emptyExpiryDate: '<?= /** @noEscape */ __('Enter an expiry date') ?>',
                monthOutOfRange: '<?= /** @noEscape */ __('Expiry month must be between 01 and 12') ?>',
                yearOutOfRange: '<?= /** @noEscape */ __('Expiry year cannot be in the past') ?>',
                dateOutOfRange: '<?= /** @noEscape */ __('Expiry date cannot be in the past') ?>',
                invalidExpiryDate: '<?= /** @noEscape */ __('Expiry date is invalid') ?>',
                emptyCVC: '<?= /** @noEscape */ __('Enter a CVC') ?>',
                invalidCVC: '<?= /** @noEscape */ __('CVC is invalid') ?>',
            },
        });
        checkout.setElements('rebill_elements');
        $('#identification-type').change(function () {
            cardHolder.identification.type = $(this).val();
            checkout.setCardHolder(cardHolder);
        });
        $('#identification-value').keyup(function () {
            cardHolder.identification.value = $(this).val();
            checkout.setCardHolder(cardHolder);
        });
    });
</script>
