<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block Subscriptions
 * @var $escaper Escaper
 */

use Improntus\Rebill\Model\Entity\Subscription\Model;
use Magento\Framework\Escaper;
use Improntus\Rebill\Block\Customer\Subscriptions;
use Magento\Framework\Pricing\Helper\Data;

/** @var Data $currencyHelper */
$currencyHelper = $this->helper(Data::class);
$subscriptions = $block->getSubscriptions();
?>
<?php if ($subscriptions->getSize()) : ?>
    <?php
    $cards = $block->getCustomerCards($subscriptions->getFirstItem()->getRebillId());
    ?>
    <div class="subscription-grid-wrapper table-wrapper">
        <table class="data table">
            <thead>
            <tr>
                <th><?= $escaper->escapeHtml(__('Subscription')) ?></th>
                <th><?= $escaper->escapeHtml(__('Quantity')) ?></th>
                <th><?= $escaper->escapeHtml(__('Status')) ?></th>
                <th><?= $escaper->escapeHtml(__('Total')) ?></th>
                <th><?= $escaper->escapeHtml(__('Iterations Remaining')) ?></th>
                <th><?= $escaper->escapeHtml(__('Payment Method')) ?></th>
                <th><?= $escaper->escapeHtml(__('Next Scheduled Payment')) ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var $subscription Model */ ?>
            <?php foreach ($subscriptions as $subscription) : ?>
                <?php $details = $subscription->getDetails() ?>
                <tr>
                    <td><?= $escaper->escapeHtml($subscription->getData('title') . ($subscription->getData('shipment') ? ' + SHIPMENT' : '')) ?></td>
                    <td><?= $escaper->escapeHtml($details['quantity']) ?></td>
                    <td><?= $escaper->escapeHtml($subscription->getStatus()) ?></td>
                    <td><?= /** @noEscape */ $currencyHelper->currencyByStore((float)$subscription->getData('price')) ?></td>
                    <td><?= $escaper->escapeHtml($details['remainingIterations']) ?></td>
                    <td><?= $escaper->escapeHtml($block->getPaymentMethod($details, $cards)) ?></td>
                    <td>
                        <?php if ($subscription->hasNextScheduledPayment()): ?>
                            <?= $escaper->escapeHtml(date('Y-m-d', strtotime($details['nextChargeDate']))) ?>
                        <?php endif; ?>
                    </td>
                    <td class="col actions">
                        <?php if ($subscription->canUpdateIt()): ?>
                        <a class="action edit"
                           href="<?= $escaper->escapeUrl($block->getUrl('rebill/customer/edit', ['id' => $details['id']])) ?>">
                            <span><?= $escaper->escapeHtml(__('Update')) ?></span>
                        </a>
                        <?php endif; ?>
                        <?php if ($subscription->canCancelIt()): ?>
                        <a class="action delete"
                           href="<?= $escaper->escapeUrl($block->getUrl('rebill/customer/cancel', ['id' => $details['id']])) ?>">
                            <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
                        </a>
                        <?php endif; ?>
                        <?php if ($subscription->canPauseIt()): ?>
                            <a class="action pause"
                               href="<?= $escaper->escapeUrl($block->getUrl('rebill/customer/pause', ['id' => $details['id']])) ?>">
                                <span><?= $escaper->escapeHtml(__('Pause')) ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($subscription->canReactivateIt()): ?>
                            <a class="action reactivate"
                               href="<?= $escaper->escapeUrl($block->getUrl('rebill/customer/reactivate', ['id' => $details['id']])) ?>">
                                <span><?= $escaper->escapeHtml(__('Reactivate')) ?></span>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <script>
        require(['jquery', 'Magento_Ui/js/modal/confirm'], function ($, confirmation) {
            $(document).ready(function () {
                $('a.delete').click(function (event) {
                    let element = $(this);
                    event.preventDefault();
                    let confirmationPopup = confirmation({
                        title: $.mage.__('Cancel Subscription'),
                        content: $.mage.__('You are about to cancel a subscription. Are you sure?'),
                        actions: {
                            confirm: function () {
                                window.location = element.attr('href');
                            },
                        },
                        buttons: [{
                            text: $.mage.__('Cancel'),
                            class: 'action-secondary action-dismiss',
                            click: function (event) {
                                this.closeModal(event);
                            }
                        }, {
                            text: $.mage.__('Ok'),
                            class: 'action primary action-accept',
                            click: function (event) {
                                this.closeModal(event, true);
                            }
                        }]
                    });
                    confirmationPopup.open();
                });

                $('a.pause').click(function (event) {
                    let element = $(this);
                    event.preventDefault();
                    let confirmationPopup = confirmation({
                        title: $.mage.__('Pause Subscription'),
                        content: $.mage.__('You are about to pause a subscription. Are you sure?'),
                        actions: {
                            confirm: function () {
                                window.location = element.attr('href');
                            },
                        },
                        buttons: [{
                            text: $.mage.__('Cancel'),
                            class: 'action-secondary action-dismiss',
                            click: function (event) {
                                this.closeModal(event);
                            }
                        }, {
                            text: $.mage.__('Ok'),
                            class: 'action primary action-accept',
                            click: function (event) {
                                this.closeModal(event, true);
                            }
                        }]
                    });
                    confirmationPopup.open();
                });

                $('a.reactivate').click(function (event) {
                    let element = $(this);
                    event.preventDefault();
                    let confirmationPopup = confirmation({
                        title: $.mage.__('Reactivate Subscription'),
                        content: $.mage.__('You are about to reactivate this subscription. Are you sure?'),
                        actions: {
                            confirm: function () {
                                window.location = element.attr('href');
                            },
                        },
                        buttons: [{
                            text: $.mage.__('Cancel'),
                            class: 'action-secondary action-dismiss',
                            click: function (event) {
                                this.closeModal(event);
                            }
                        }, {
                            text: $.mage.__('Ok'),
                            class: 'action primary action-accept',
                            click: function (event) {
                                this.closeModal(event, true);
                            }
                        }]
                    });
                    confirmationPopup.open();
                });
            });
        });
    </script>
<?php else : ?>
    <div class="subscription-grid-wrapper table-wrapper">
        <span class="no-subscriptions"><?= /** @noEscape */
            __('You have no active subscriptions') ?></span>
    </div>
<?php endif; ?>
