<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block Subscriptions
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Block\Customer\Subscriptions;
use Magento\Framework\Pricing\Helper\Data;

/** @var Data $currencyHelper */
$currencyHelper = $this->helper(Data::class);
$subscriptions = $block->getSubscriptions() ?? [];
?>
<?php if ($subscriptions) : ?>
    <div class="subscription-grid-wrapper table-wrapper">
        <table class="data table">
            <thead>
            <tr>
                <th><?= $escaper->escapeHtml(__('Subscription')) ?></th>
                <th><?= $escaper->escapeHtml(__('Quantity')) ?></th>
                <th><?= $escaper->escapeHtml(__('Status')) ?></th>
                <th><?= $escaper->escapeHtml(__('Total')) ?></th>
                <th><?= $escaper->escapeHtml(__('Payment Method')) ?></th>
                <th><?= $escaper->escapeHtml(__('Created at')) ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $subscription) : ?>
                <tr>
                    <td><?= $escaper->escapeHtml($subscription['title']) ?></td>
                    <td><?= $escaper->escapeHtml($subscription['quantity']) ?></td>
                    <td><?= $escaper->escapeHtml($subscription['status']) ?></td>
                    <td><?= $currencyHelper->currencyByStore((float)$subscription['price']['amount']) ?></td>
                    <td><?= $escaper->escapeHtml($block->getPaymentMethod($subscription)) ?></td>
                    <td><?= $escaper->escapeHtml(date('Y-m-d', strtotime($subscription['createdAt']))) ?></td>
                    <td class="col actions">
                        <a class="action edit" href="<?= $escaper->escapeUrl($block->getUrl('rebill/customer/edit', ['id' => $subscription['id']])) ?>">
                            <span><?= $escaper->escapeHtml(__('Update')) ?></span>
                        </a>
                        <a class="action delete" href="<?= $escaper->escapeUrl($block->getUrl('rebill/customer/cancel', ['id' => $subscription['id']])) ?>">
                            <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <script>
        require(['jquery', 'Magento_Ui/js/modal/confirm'], function ($, confirmation) {
            $(document).ready(function () {
                $('a.delete').click(function (event) {
                    let element = $(this);
                    event.preventDefault();
                    let confirmationPopup = confirmation({
                        title: $.mage.__('Cancel Subscription'),
                        content: $.mage.__('You are about to cancel a subscription. Are you sure?'),
                        actions: {
                            confirm: function() {
                                window.location = element.attr('href');
                            },
                        },
                        buttons: [{
                            text: $.mage.__('Cancel'),
                            class: 'action-secondary action-dismiss',
                            click: function (event) {
                                this.closeModal(event);
                            }
                        }, {
                            text: $.mage.__('Ok'),
                            class: 'action primary action-accept',
                            click: function (event) {
                                this.closeModal(event, true);
                            }
                        }]
                    });
                    confirmationPopup.open();
                })
            });
        });
    </script>
<?php else : ?>
<div class="subscription-grid-wrapper table-wrapper">
    <span class="no-subscriptions"><?= /** @noEscape */__('You have no active subscriptions') ?></span>
</div>
<?php endif; ?>
