<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block Subscriptions
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Block\Customer\Subscriptions;
use Magento\Framework\Pricing\Helper\Data;

/** @var Data $currencyHelper */
$currencyHelper = $this->helper(Data::class);
$subscriptions = $block->getSubscriptions() ?? [];
?>
<?php if ($subscriptions) : ?>
    <div class="subscription-grid-wrapper table-wrapper">
        <table class="data table">
            <thead>
            <tr>
                <th><?= /** @noEscape */__('Subscription') ?></th>
                <th><?= /** @noEscape */__('Quantity') ?></th>
                <th><?= /** @noEscape */__('Status') ?></th>
                <th><?= /** @noEscape */__('Total') ?></th>
                <th><?= /** @noEscape */__('Payment Method') ?></th>
                <th><?= /** @noEscape */__('Created at') ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $subscription) : ?>
                <tr>
                    <td><?= $escaper->escapeHtml($subscription['title']) ?></td>
                    <td><?= $escaper->escapeHtml($subscription['quantity']) ?></td>
                    <td><?= $escaper->escapeHtml($subscription['status']) ?></td>
                    <td><?= $escaper->escapeHtml($currencyHelper->currencyByStore((float)$subscription['price']['amount'])) ?></td>
                    <td><?= $escaper->escapeHtml($block->getPaymentMethod($subscription)) ?></td>
                    <td><?= $escaper->escapeHtml(date('Y-m-d', strtotime($subscription['createdAt']))) ?></td>
                    <td class="col actions">
                        <a class="action delete"
                           href="<?= /** @noEscape */$block->getUrl('rebill/customer/cancel', ['id' => $subscription['id']]) ?>"><?= /** @noEscape */__('Cancel') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else : ?>
<div class="subscription-grid-wrapper table-wrapper">
    <span class="no-subscriptions"><?= /** @noEscape */__('You have no active subscriptions') ?></span>
</div>
<?php endif; ?>
