<?php
/**
 * @var $block Transaction
 */

use Improntus\Rebill\Block\Payment\Transaction;

$rebillTransaction = $block->getRebillTransaction();
?>
<div id="rebill-transaction-wrapper">
    <div class="rebill-transaction-container" data-bind="scope: 'rebill'">
        <h2 class="rebill.payment.transaction.title"><!-- ko i18n: 'Pay with rebill' --><!-- /ko --></h2>

        <div class="rebill-cardholder-field">
            <div class="value">
                <label for="cardholder-name"><!-- ko i18n: 'Card Holder' --><!-- /ko --></label>
                <input type="text" id="cardholder-name" name="cardholder_name"
                       data-bind="event: {keyup: function (data, event) {changeCardHolderName(event)}}">
            </div>
        </div>

        <!-- ko if: needCardHolderIdentification() -->
        <div class="rebill-identification-field">
            <div class="type">
                <label for="identification-type"><!-- ko i18n: 'Document Type' --><!-- /ko --></label>
                <select name="identification_type" id="identification-type"
                        data-bind="options: documentTypes, event: {change: function (data, event) {selectDocumentType(event)}}"></select>
            </div>
            <div class="value">
                <label for="identification-value"><!-- ko i18n: 'Document Number' --><!-- /ko --></label>
                <input type="text" id="identification-value" name="identification_value"
                       data-bind="event: {keyup: function (data, event) {changeDocumentNumber(event)}}">
            </div>
        </div>
        <!-- /ko -->
        <div id="rebill_elements"></div>
        <div class="rebill-errors"></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#rebill-transaction-wrapper": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "rebill": <?= json_encode($rebillTransaction) ?>
                }
            }
        }
    }

</script>
