<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block View
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Helper\Config;
use Magento\Catalog\Block\Product\View;

/** @var Config $configHelper */
$configHelper = $this->helper(Config::class);
$productRebill = $configHelper->getProductRebillSubscriptionDetails($block->getProduct());
$frequencies = $productRebill['frequency'];
$isOnlySubscription = $productRebill['subscription_type'] === "subscription";
?>
<?php if (($count = count($frequencies)) && $configHelper->isLoggedIn()) : ?>
    <div class="rebill-subscription">
        <?php if (!$isOnlySubscription) : ?>
            <div class="check-subscription">
                <input type="radio" name="use_subscription" value="0" id="one-time-purchase" checked="checked">
                <label for="one-time-purchase">
                    <?= /** @noEscape */
                    __('One time purchase') ?>
                </label>
            </div>
        <?php endif ?>
        <div class="check-subscription">
            <input type="radio" name="use_subscription" value="1" id="use-subscription">
            <label for="use-subscription">
                <?php if ($count === 1) : ?>
                    <?= /** @noEscape */
                    __('Subscribe to this product %1', $configHelper->getFrequencyDescription($block->getProduct(), reset($frequencies))) ?>
                <?php else : ?>
                    <?= /** @noEscape */
                    __('Subscribe to this product') ?>
                <?php endif ?>
            </label>
        </div>
        <div class="description" style="display: none">
            <?php if ($count === 1) : ?>
                <input type="hidden" name="frequency" value="<?= /** @noEscape */
                array_first($frequencies)['id'] ?>">
            <?php else : ?>
                <span class="option">
                    <select name="frequency" id="frequency">
                        <?php foreach ($frequencies as $frequency) : ?>
                            <option value="<?= /** @noEscape */ $frequency['id'] ?>"
                                    data-price="<?= /** @noEscape */ $configHelper->getFrequencyPriceFormat((float)$frequency['price']); ?>">
                                <?= /** @noEscape */ $configHelper->getFrequencyDescription($block->getProduct(), $frequency) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </span>
            <?php endif ?>
        </div>
    </div>
    <script>
        require(['jquery'], function ($) {
            $(document).ready(function () {
                let productOriginalPrice = $("span.price").html();
                let cartButton = $("#product-addtocart-button");
                let cartText = cartButton.text();
                $("#use-subscription").click(function () {
                    $(".rebill-subscription .description").show();
                    cartButton.text("<?= $escaper->escapeJs($configHelper->getSubscriptionProductText()) ?>");
                });
                if(<?= $isOnlySubscription ?>){
                    $(".rebill-subscription .description").show();
                    $("#use-subscription")[0].checked= true;
                    cartButton.text("<?= $escaper->escapeJs($configHelper->getSubscriptionProductText()) ?>");
                }
                $("#one-time-purchase").click(function () {
                    // Restore original Price
                    $("span.price").html(productOriginalPrice);
                    $(".rebill-subscription .description").hide();
                    cartButton.text(cartText);
                });
                setInterval(function () {
                    addFrequencyPrice();
                }, 100);

                function addFrequencyPrice(){
                    let frequencyPrice = $("#frequency").find('option:selected').data('price');
                    let frequencyOperator = frequencyPrice.indexOf("-") === -1 ? " +" : " ";
                    if ($('#one-time-purchase').is(':checked')) {
                        frequencyPrice = "0";
                    }
                    if (containsZeroPrice(frequencyPrice)) {
                        $("span.price").html(productOriginalPrice);
                    } else {
                        $("span.price").html(productOriginalPrice + frequencyOperator + frequencyPrice);
                    }
                }

                function containsZeroPrice(price) {
                    return parseFloat(price.replace(/\D/g, '')) === 0;
                }
            });
        });
    </script>
<?php endif ?>
