<?php
/**
 * @var \Improntus\Rebill\Block\Onepage\Success $block
 * @var $escaper \Magento\Framework\Escaper
 */
$order = $block->getOrder();
$payment = $order->getPayment();
$additionalInformation = $payment->getAdditionalInformation();
?>
<?php if($payment->getMethod()  == \Improntus\Rebill\Model\Payment\Rebill::CODE):?>
    <img style="width: 100px;margin-bottom: 20px;" src="" alt="">
    <p><a onclick="this.target='_blank'" href=""><?= /** @noEscape */__('Print Payment')?></a></p>
<?php endif; ?>
