<?php
/**
 * @author Improntus Dev Team
 * @copyright Copyright (c) 2022 Improntus (http://www.improntus.com/)
 * @package Improntus_Rebill
 */

/**
 * @var $block View
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use Improntus\Rebill\Helper\Config;
use Magento\Catalog\Block\Product\View;

/** @var Config $configHelper */
$configHelper = $this->helper(Config::class);
$frequencies = $configHelper->getProductRebillSubscriptionDetails($block->getProduct())['frequency'];
?>
<?php if (($count = count($frequencies)) && $configHelper->isLoggedIn()) : ?>
    <div class="rebill-subscription">
        <div class="check-subscription">
            <input type="radio" name="use_subscription" value="0" id="one-time-purchase" checked="checked">
            <label for="one-time-purchase">
                <?= /** @noEscape */
                __('One time purchase') ?>
            </label>
        </div>
        <div class="check-subscription">
            <input type="radio" name="use_subscription" value="1" id="use-subscription">
            <label for="use-subscription">
                <?php if ($count === 1) : ?>
                    <?= /** @noEscape */
                    __('Subscribe to this product %1', $configHelper->getFrequencyDescription($block->getProduct(), array_first($frequencies))) ?>
                <?php else : ?>
                    <?= /** @noEscape */
                    __('Subscribe to this product') ?>
                <?php endif ?>
            </label>
        </div>
        <div class="description" style="display: none">
            <?php if ($count === 1) : ?>
                <input type="hidden" name="frequency" value="<?= /** @noEscape */
                array_first($frequencies)['id'] ?>">
            <?php else : ?>
                <span class="option">
                    <select name="frequency" id="frequency">
                        <?php foreach ($frequencies as $frequency) : ?>
                            <option value="<?= /** @noEscape */
                            $frequency['id'] ?>" data-price="<?= /** @noEscape */
                            $configHelper->getFrequencyPriceFormat($frequency['price']); ?>"><?= /** @noEscape */
                                $configHelper->getFrequencyDescription($block->getProduct(), $frequency) ?></option>
                        <?php endforeach; ?>
                    </select>
                </span>
            <?php endif ?>
        </div>
    </div>
    <script>
        require(['jquery'], function ($) {
            $(document).ready(function () {
                let productOriginalPrice = $("span.price").html();
                let cartButton = $("#product-addtocart-button");
                let cartText = cartButton.text();
                $("#use-subscription").click(function () {
                    // Update Price
                    addFrequencyPrice("#frequency");
                    $(".rebill-subscription .description").show();
                    cartButton.text("<?= $escaper->escapeJs($configHelper->getSubscriptionProductText()) ?>");
                });
                $("#one-time-purchase").click(function () {
                    // Restore original Price
                    $("span.price").html(productOriginalPrice);
                    $(".rebill-subscription .description").hide();
                    cartButton.text(cartText);
                });
                $("#frequency").change(function () {
                    addFrequencyPrice(this);
                })

                function addFrequencyPrice(el) {
                    let frequencyPrice = $(el).find('option:selected').data('price');
                    let frequencyOperator = frequencyPrice.indexOf("-") === -1 ? " +" : " ";

                    if (containsZeroPrice(frequencyPrice)) {
                        $("span.price").html(productOriginalPrice);
                    } else {
                        $("span.price").html(productOriginalPrice + frequencyOperator + frequencyPrice);
                    }
                }

                function containsZeroPrice(price) {
                    return parseFloat(price.replace(/\D/g, '')) === 0;
                }


            });
        });
    </script>
<?php endif ?>
